spring.application.name=frontoffice
server.port=8081

# REMPLACER 'IP_BACKOFFICE' par l'adresse IP r\u00e9elle de la machine distante
# Exemple: http://192.168.1.50:8080/api/reservations
backoffice.api.url=http://localhost:8080/reservation-core/api/reservations

# URL pour valider le token auprès du BackOffice
backoffice.token.validation.url=http://localhost:8080/reservation-core/voir-token
